//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public long ID { get; set; }
        public decimal Price { get; set; }
        public bool Confirmed { get; set; }
        public long ClassApplicationID { get; set; }
    
        public virtual ClassApplication ClassApplication { get; set; }
    }
}
