//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Top { get; set; }
        public Nullable<int> Left { get; set; }
        public Nullable<long> ClassroomID { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
    
        public virtual Classroom Classroom { get; set; }
    }
}
