//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeachableSubject
    {
        public long ID { get; set; }
        public long InstructorID { get; set; }
        public long SubjectID { get; set; }
    
        public virtual Subject Subject { get; set; }
        public virtual Instructor Instructor { get; set; }
    }
}
